vertex:
  project_id: realtime-stems
  project_number: "69797308691"
  region: us-central1
  staging_bucket: gs://realtime-stems/staging
  container_uri: us-central1-docker.pkg.dev/realtime-stems/realtime-stems-repo/hs-tasnet:latest
  service_account: vertex-jobs@realtime-stems.iam.gserviceaccount.com
  network: null
  model_serving_container: us-docker.pkg.dev/vertex-ai/prediction/pytorch-gpu.2-0:latest

  train:
    job_display_name: hs-tasnet-train
    model_display_name: hs-tasnet-model
    cfg: src/hs_tasnet/config/train.yaml
    dataset_uri: gs://realtime-stems/musdb18
    base_output_dir: gs://realtime-stems-model-artifacts
    gcs_runs_uri: gs://realtime-stems-model-artifacts/runs
    machine_type: g2-standard-4
    accelerator_type: NVIDIA_L4
    accelerator_count: 1
    replica_count: 1

  eval:
    job_display_name: hs-tasnet-eval
    cfg: src/hs_tasnet/config/eval.yaml
    dataset_uri: gs://realtime-stems/musdb18
    model_uri: gs://realtime-stems-model-artifacts/model
    model_resource_name: projects/69797308691/locations/us-central1/models/6917439967199232000
    eval_output_uri: gs://realtime-stems-model-artifacts/evaluations/hs-tasnet-musdb18-test
    evaluation_display_name: musdb18-test
    metrics_schema_uri: null
    metrics_schema_local_path: src/hs_tasnet/config/vertex_model_evaluation_metrics.yaml
    machine_type: g2-standard-4
    accelerator_type: NVIDIA_L4
    accelerator_count: 1
    replica_count: 1
    boot_disk_size_gb: 200
