base: paper_hs_tasnet.yaml

train:
  epochs: 10
  batch_size: 4
  grad_accum_steps: 1
  lr: 0.001

data:
  loader: "musdb"
  musdb_root: /mnt/data/musdb18
  musdb_is_wav: false
  musdb_val_subset: "train"
  musdb_val_split: "valid"
  tiny_dataset: false
